# Generated by Django 4.1.4 on 2023-01-21 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movieapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Place", new_name="Movie",),
    ]
