# Generated by Django 4.1.4 on 2023-01-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movieapp", "0002_rename_place_movie"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="img",
            field=models.ImageField(default="dfggh", upload_to="gallery"),
            preserve_default=False,
        ),
    ]
